### ISSUE TITLE
Email notification

### ISSUE THREAD

**Issue by claytoncollie** [thingsym/wp-auto-updater#2]
Hi. I just found this plugin and really like how simple it is. One thing I do think it is missing though is an email notification. I researched Easy Plugin Update and also the WP Autoudpates that will be merged into Core later this year. Both have this functionality to send to the admin_email when updates are made.

Are you interested in add this functionality?

**Comment by thingsym** [comment]
Hi @claytoncollie,

Thank you for your issue.

Yes. I interest email notification.
I would like to implement email notifications.

**Comment by thingsym** [comment]
Email notifications have been implemented in version 1.4.0 and version 1.5.0.
